server:
  port: 8084
spring:
  data:
      mongodb:
        user: 
        password: 
        uri: mongodb://localhost:8082/proyecto2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
