server:
  port: 8084
spring:
  data:
      mongodb:
        uri: mongodb://nttdata:nttd4t4@localhost:27017/Proyecto1MongoDB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
